name: Update Model

on: 
  pull_request:

jobs:
  pull-into-main:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Switch branch
        run: git switch dev
  
